services:
  - type: web
    name: salexpress-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
